### ISSUE TITLE
autorenew?

### ISSUE THREAD

**Issue by adespain** [cchurch/ansible-role-letsencrypt#1]
Does this auto renew certs every 90 days, or does this playbook need to be run every 90 days?  certbot uses cron, so just wondering if the ansible letsencrypt module does that in the background somehow?

**Comment by cchurch** [comment]
This role is mostly just a wrapper about the Ansible `letsencrypt` module, which doesn't use certbot or setup any cron jobs. It needs to be run periodically to renew certs.

I haven't yet made `remaining_days` a configurable option, so it uses the default of 10. If run with more than that many days remaining, it will only check the cert and skip the renewal process with no changes.
